module.exports = {
  "spreadsheetId": "1zwtuoozCw-8iGHFhJiolPz0Loy4sk17mHffVorw2z1s",
  "valueRanges": [
    {
      "range": "categories!A1:Y1008",
      "majorDimension": "COLUMNS",
      "values": [
        [
          "Boice",          "FALSE",          "Boice, Boice, Boice, Boice, Boice, Boice, Boice? Boice!",          "Anand",          "Neeraj",          "Amar",          "Amit",          "Sid",          "Bharat",          "Nirbhay",          "Rachit",          "Neil",          "Pranav",          "Utsav",          "Anwesh",          "Samir",          "Rajeev",          "1738",          "INSANNNNNNNNNEEE",          "GP",          "2BM",          "2G",          "Boice",          "Bewafa",          "Nema",          "Runnable",          "SF",          "Mission",          "Avalon",          "Taco Bell",          "888",          "Bootie",          "Red Flags",          "Yaawwww dude",          "AIO",          "beer pong",          "social",          "unofficial",          "masti",          "chai town",          "one night in vegas",          "litty",          "bollywood",          "Natu Natu",          "Tollywood",          "YOLO",          "Sex Karenge",          "Yeezy",          "Rolls down the hill",          "sports",          "Molly",          "no flex zone",        ],
        [
          "Disneyland", "FALSE", "The magic you can experience at Disneyland", "Disney California Adventure", "Soarin' Over California", "Guardians of the Galaxy: Mission BREAKOUT!", "Incredicoaster", "Mickey's Toontown", "Soarin' Around the World", "Funnel Cake", "Pirates of the Carribean", "Turtle Talk With Crush", "Big Thunder Mountain Railroad", "Star Tours", "Space Mountain", "Star Wars Launch Bay", "Buzz Lightyear's Astro Blasters", "Toy Story Midway Mania!", "Alice in Wonderland", "Mr. Toad's Wild Ride", "Astro Orbiter", "Autopia", "Casey Jr. Circus Train", "Monorail", "Great Moments with Mr. Lincoln", "Tower of Terror", "Mickey and Minnie's Runaway Railway", "Millennium Falcon: Smugglers Run", "Haunted Mansion", "Indiana Jones™ Adventure", "Inside Out Emotional Whirlwind", "\"it's a small world\"", "Fireworks", "Main Street Electrical Parade", "Paint the Night", "Jungle Cruise", "Ariel's Undersea Adventure", "Mad Tea Party", "Mark Twain Riverboat", "Matterhorn Bobsleds", "Peter Pan's Flight", "Pinocchio's Daring Journey", "Tom Sawyer Island", "Radiator Springs Racers", "Sailing Ship Columbia", "Sleeping Beauty's Castle", "Snow White's Scary Adventures", "Splash Mountain", "Walt Disney's Enchanted Tiki Room", "Disneyland Park", "Adventureland", "Tomorrowland", "New Orleans Square", "Frontierland", "Critter Country", "Main Street, U.S.A.", "Disneyland Railroad", "The Many Adventures of Winnie the Pooh", "FastPass", "Dole Whip", "Hidden Mickeys", "Fantasmic!", "Dumbo the Flying Elephant", "Disney's Grand Californian", "The Disneyland Hotel", "Disney's Paradise Pier Hotel", "Pixar Pier", "The Dapper Dans", "Disneyland Forever", "World of Color"
        ],
        [
          "Walt Disney World",
          "FALSE",
          "The magic you can experience at Walt Disney World",
          "Frozen Ever After",
          "Journey Into Imagination With Figment",
          "Living with the Land",
          "Mission: SPACE",
          "The Seas with Nemo & Friends",
          "Soarin' Around the World",
          "Spaceship Earth",
          "Test Track",
          "Turtle Talk With Crush",
          "Flower & Garden Festival",
          "International Food & Wine Festival",
          "Canada",
          "United Kingdom",
          "France",
          "Morocco",
          "Japan",
          "The American Adventure (United States)",
          "Italy",
          "Germany",
          "China",
          "Norway",
          "Mexico",
          "Le Cellier",
          "Biergarten",
          "Chefs de France",
          "Coral Reef Restaurant",
          "Funnel Cake",
          "IllumiNations",
          "La Hacienda de San Angel",
          "Nine Dragons Restaurant",
          "Rose & Crown",
          "Via Napoli",
          "Drinking Around The World",
          "Experimental Prototype Community of Tomorrow",
          "World Showcase",
          "Future World",
          "ticket and transportation center",
          "Friendship Launch",
          "Joffrey's",
          "Mouse Gear",
          "Alien Swirling Saucers",
          "Lightning McQueen's Racing Academy ",
          "Muppet*Vision 3D",
          "Rock 'n' Roller Coaster",
          "Slinky Dog Dash",
          "Star Tours ",
          "Star Wars Launch Bay",
          "Toy Story Mania!",
          "Tower of Terror",
          "Walt Disney Presents",
          "Mickey and Minnie's Runaway Railway",
          "Millennium Falcon: Smugglers Run",
          "Star Wars: Path of the Jedi",
          "Indiana Jones™ Epic Stunt Spectacular!",
          "50's Prime Time Café",
          "Tatooine Traders",
          "PizzeRizzo",
          "Sci-Fi Dine-in Theatre Restaurant",
          "Woody's Lunch Box",
          "Voyage of The Little Mermaid",
          "Beauty and the Beast—Live on Stage",
          "Toy Story Land",
          "Roundup Rodeo BBQ",
          "Hollywood & Vine",
          "For the First Time in Forever: A Frozen Sing-Along Celebration",
          "Main Street, U.S.A.",
          "Casey's Corner",
          "The Crystal Palace",
          "Swiss Family Treehouse",
          "The Magic Carpets of Aladdin",
          "Walt Disney's Enchanted Tiki Room",
          "Jungle Cruise",
          "Pirates of the Caribbean",
          "Aloha Isle",
          "Tortuga Tavern",
          "Splash Mountain ",
          "Big Thunder Mountain Railroad",
          "Tom Sawyer Island",
          "Country Bear Jamboree",
          "The Hall of Presidents",
          "Haunted Mantion",
          "Bibbidi Bobbidi Boutique",
          "\"it's a small world\"",
          "Peter Pan's Flight",
          "Mickey's PhilharMagic",
          "The Many Adventures of Winnie the Pooh",
          "Mad Tea Party",
          "Dumbo the Flying Elephant",
          "The Barnstormer",
          "Cinderella's Royal Table",
          "Cinderella's Castle",
          "Tomorrowland Speedway",
          "Space Mountain",
          "Astro Orbiter",
          "PeopleMover",
          "Walt Disney's Carousel of Progress",
          "Buzz Lightyear's Space Ranger Spin",
          "Sitch's Great Escape!",
          "Monsters, Inc. Laugh Floor",
          "Cosmic Ray's Starlight Cafe",
          "The Lunching Pad",
          "Dole Whip",
          "Main Street Electrical Parade",
          "Monorail",
          "Disney Skyliner",
          "Rainforest Cafe",
          "It's Tough to be a Bug!",
          "Tiffins",
          "Na'vi River Journey",
          "Avatar Flight of Passage",
          "Festival of the Lion King",
          "Kilimanjaro Safaris",
          "Tusker House Restaurant",
          "Kali River Rapids",
          "Expedition Everest",
          "DINOSAUR",
          "Rivers of Light",
          "Yak & Yeti Restaurant",
          "Finding Nemo - The Musical",
          "Primeval Whirl",
          "TriceraTop Spin",
          "Dinoland U.S.A",
          "Discovery Island",
          "Pandora - The World of Avatar",
          "All-Star Movies Resort",
          "All-Star Music Resort",
          "All-Star Sports Resort",
          "Art of Animation Resort",
          "Pop Century Resort",
          "Fort Wilderness Resort",
          "Caribbean Beach Resort",
          "Coronado Springs Resort",
          "Port Orleans Resort - French Quarter",
          "Port Orleans Resort - Riverside",
          "Animal Kingdom Lodge",
          "Beach Club Resort",
          "BoardWalk Inn",
          "Contemporary Resort",
          "Grand Floridian Resort & Spa",
          "Polynesian Village Resort",
          "Wilderness Lodge",
          "Yacht Club Resort",
          "Bay Lake Tower",
          "Old Key West Resort",
          "Riviera Resort",
          "Saratoga Springs Resort & Spa",
          "Disney Springs",
          "ESPN Wide World of Sports Complex",
          "Blizzard Beach",
          "Typhoon Lagoon",
          "Lake Buena Vista",
          "Magic Kingdom",
          "Animal Kingdom",
          "Hollywood Studios",
          "Epcot",
          "Seven Dwarfs Mine Train",
          "Gran Fiesta Tour",
          "Under the Sea: Journey of The Little Mermaid",
          "Hidden Mickeys",
          "Fantasmic!",
          "Happily Ever After",
          "IllumiNations: Reflections of Earth",
          "Star Wars: A Galactic Spectacular",
          "MagicBand",
          "Fast Pass",
          "Extra Magic Hours",
          "Hoop-Dee-Doo Musical Revue",
          "Tree of Life",
          "Yo Ho Yo Ho, A Pirates Life for Me",
          "Funnel Cake",
          "Tomorrowland",
          "Frontierland",
          "The Little Mermaid: Ariel's Undersea Adventure",
          "Adventureland",
          "Fireworks",
          "Tinker Bell"
        ],
        [
          "Disney Characters for Kids",          "FALSE",          "Images of Disney Characters. Great for younger kids!",          "elsa",          "piglet",          "olaf",          "anna",          "winnie_the_pooh",          "elena",          "ariel",          "aurora",          "belle",          "cinderella",          "jasmine",          "merida",          "mulan",          "pocahontas",          "rapunzel",          "snow_white",          "tiana",          "daisy_duck",          "donald_duck",          "goofy",          "mickey_mouse",          "minnie_mouse",          "pluto",          "tigger",          "captain_jack_sparrow",          "lightning_mcqueen",          "vidia",          "guido",          "rex",          "owl",          "christopher_robin",          "woody",          "eeyore",          "buzz_lightyear",          "mr._potato_head",          "hamm",          "rabbit",          "fawn",          "slinky_dog",          "silvermist",          "iridessa",          "aliens",          "rosetta",          "jessie",          "kanga_&_roo",          "simba",          "hans",          "kristoff",          "duke_of_weselton",          "marshmallow",          "oaken",          "olaf",          "snowgies",          "sven",          "scar",          "timon",          "pumba",          "mufasa",          "rafiki",          "nala",          "zasu",          "ariel",          "bruce",          "crush",          "dory",          "flounder",          "king_triton",          "peach",          "prince_eric",          "scuttle",          "sebastian",          "squirt",          "ursula",          "aladdin",          "carpet",          "genie",          "iago",          "jafar",          "jasmine",          "rajah",          "sultan",          "moana",          "maui",          "heihei"        ],
        [
          "Ladies of Disney for Kids",          "FALSE",          "Images of Disney Princesses and other ladies!",          "elsa",          "ariel",          "aurora",          "anna",          "belle",          "cinderella",          "jasmine",          "merida",          "mulan",          "pocahontas",          "rapunzel",          "snow_white",          "tiana",          "atta",          "lilo",          "nala",          "moana",          "daisy_duck",          "minnie_mouse",          "elena",          "fawn",          "silvermist",          "vidia",          "ursula",          "peach",          "jessie",          "dory",          "bambi",          "tinker_bell",          "bo_peep",          "boo",          "alice",          "maleficent"        ],
        [
          "Walt Disney World Characters",          "FALSE",          "The characters you can run into at Walt Disney World",          "Aladdin",          "Alice",          "Anastasia",          "Anna",          "Ariel",          "Aurora",          "Baloo",          "Beast",          "Belle",          "Bert (Mary Poppins)",          "Brer Rabbit",          "Brer Bear",          "Brer Fox",          "Buzz Lightyear",          "Captain Hook",          "Chewbacca",          "Chip & Dale",          "Cinderella",          "Cruella De Ville",          "Daisy Duck",          "Donald Duck",          "Drizella",          "Dwarfs",          "Eeyore",          "Elsa",          "Evil Queen",          "Fairy Godmother",          "Flik",          "Friar Tuck",          "Frollo",          "Genie",          "Geppetto",          "Gideon",          "Goofy",          "Gov Radcliffe",          "Green Army Men",          "Hercules",          "J.Worthington Foulfellow",          "Jafar",          "Jane Porter (Tarzan)",          "Jasmine",          "Jessie",          "Jiminy Cricket",          "Kermit",          "King Louie",          "Launchpad McQuack",          "Lady Tremaine",          "Little John",          "Liverlips",          "Mad Hatter",          "Malificent",          "Mary Poppins",          "Max, Goofy's Son",          "Meeko",          "Meg (Hercules)",          "Mickey Mouse",          "Minnie Mouse",          "Miss Piggy",          "Mowgli",          "Mr Smee",          "Mulan",          "Mushu",          "Peter Pan",          "Phoebus",          "Piglet",          "Pinnochio",          "Pluto",          "Pocahontas",          "Pooh",          "Prince Charming",          "Prince John",          "Princess Aurora",          "Princess Atta",          "Quasimodo",          "Queen of Hearts",          "Rafiki",          "Red Queen",          "Robin Hood",          "Scrooge McDuck",          "Shaker (Country Bear)",          "Shan-Yu",          "Sheriff of Nottingham",          "Snow White",          "Snow White Evil Queen",          "Stromboli (Pinnochio)",          "Suzy & Perla",          "Tarzan",          "Terk",          "Tigger",          "Timon",          "Tweedle Dum/Dee",          "Wendell",          "White Rabbit / March Hare",          "Wicked Witch",          "Wendy",          "Woody",          "Flynn Rider",          "Kylo Ren",          "Lilo",          "Olaf",          "Stitch",          "Captain Jack Sparrow",          "SleepingBeauty"
        ],
        [
          "Disney Movies",          "FALSE",          "The latest and greatest Disney Movies (post-2009)",          "Alice in Wonderland",          "Prince of Persia: The Sands of Time",          "Toy Story 3",          "Tangled",          "Tron: Legacy",          "Pirates of the Caribbean: On Stranger Tides",          "Cars 2",          "Winnie the Pooh",          "The Muppets",          "Brave",          "Arjun: The Warrior Prince",          "Wreck-It Ralph",          "Monsters University",          "The Lone Ranger",          "Planes",          "Frozen",          "Maleficent",          "Big Hero 6",          "Into the Woods",          "Cinderella",          "Tomorrowland",          "Inside Out",          "The Good Dinosaur",          "Zootopia",          "The Jungle Book",          "Alice Through the Looking Glass",          "Finding Dory",          "The BFG",          "Pete's Dragon",          "Moana",          "Beauty and the Beast",          "Pirates of the Caribbean: Dead Men Tell No Tales",          "Cars 3",          "Coco",          "A Wrinkle in Time",          "Incredibles 2",          "Ralph Breaks the Internet",          "Aladdin",          "Dumbo",          "Toy Story 4",          "The Lion King",          "Star Wars: The Last Jedi",          "Marvel’s The Avengers",          "Iron Man 3",          "Thor: The Dark World",          "Avengers: Age of Ultron",          "Star Wars: The Force Awakens",          "Captain America: Civil War",          "Rogue One: A Star Wars Story",          "Guardians of the Galaxy, Vol. 2",          "Thor: Ragnarok ",          "Black Panther",          "Solo: A Star Wars Story",          "Ant-Man and The Wasp",          "Avengers: Endgame",          "Captain Marvel"        ],
        [
          "Classic Disney Movies",          "FALSE",          "The classic Disney movies (pre-2009)",          "Snow White and the Seven Dwarfs",          "Pinocchio",          "Fantasia",          "Dumbo",          "Bambi",          "Treasure Island",          "Cinderella",          "Alice in Wonderland",          "Peter Pan",          "20,000 Leagues Under the Sea",          "Lady and the Tramp",          "Sleeping Beauty",          "The Parent Trap",          "101 Dalmatians",          "Mary Poppins",          "The Jungle Book",          "The Aristocats",          "The Rescuers Down Under",          "Beauty and the Beast",          "Honey, I Blew Up the Kid",          "The Mighty Ducks",          "Aladdin",          "Homeward Bound: The Incredible Journey",          "Hocus Pocus",          "Cool Runnings",          "The Lion King",          "Angels in the Outfield",          "The Santa Clause ",          "The Jungle Book",          "Heavyweights",          "A Goofy Movie",          "Pocahontas",          "A Kid in King Arthur's Court",          "Toy Story",          "Tom and Huck",          "Muppet Treasure Island",          "James and the Giant Peach",          "The Hunchback of Notre Dame",          "101 Dalmatians",          "Hercules",          "George of the Jungle",          "Air Bud",          "Flubber",          "Mulan",          "A Bug's Life",          "Tarzan",          "Inspector Gadget",          "Freaky Friday",          "The Many Adventures of Winnie the Pooh",          "Popeye",          "The Fox and the Hound",          "Tron",          "Honey, I Shrunk the Kids",          "The Little Mermaid",          "White Fang",          "Fantasia 2000",          "The Tigger Movie",          "Dinosaur",          "Remember the Titans",          "102 Dalmatians",          "The Emperor's New Groove",          "Recess: School's Out",          "Atlantis: The Lost Empire",          "The Princess Diaries",          "Monsters, Inc.",          "Snow Dogs",          "Return to Never Land",          "Lilo & Stitch",          "The Country Bears",          "Tuck Everlasting",          "The Santa Clause 2",          "Treasure Planet",          "Holes",          "The Lizzie McGuire Movie",          "Finding Nemo",          "Pirates of the Caribbean: The Curse of the Black Pearl",          "Miracle",          "Confessions of a Teenage Drama Queen",          "The Incredibles",          "National Treasure",          "Ice Princess",          "The Pacifier",          "Herbie: Fully Loaded",          "Sky High",          "Chicken Little",          "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",          "Cars",          "Pirates of the Caribbean: Dead Man's Chest",          "Invincible",          "The Santa Clause 3: The Escape Clause",          "Pirates of the Caribbean: At World's End",          "Ratatouille",          "Enchanted",          "WALL-E",          "High School Musical",          "Bolt",          "Up",          "The Princess nd the Frog"
        ],
        [
          "Classic Disney Channel Original Movies",
          "FALSE",
          "The classic Disney Channel Original Movies (pre-2006)",
          "Airborne",
          "Escape to Witch Mountain",
          "Susie Q",
          "Wish Upon A Star",
          "The Paper Brigade",
          "Brink!",
          "Halloweentown",
          "Zenon: Girl of the 21st Century",
          "The Thirteenth Year",
          "Smart House",
          "Johnny Tsunami",
          "Genius",
          "Don't Look Under the Bed",
          "Horse Sense",
          "Up, Up, and Away",
          "The Color of Friendship",
          "Alley Cats Strike",
          "Rip Girls",
          "Miracle in Lane 2",
          "Stepsister from Planet Weird",
          "Mom's Got a Date with a Vampire",
          "Phantom of the Megaplex",
          "Zenon: The Zequel",
          "Motocrossed",
          "The Luck of the Irish",
          "Hounded",
          "Jett Jackson: The Movie",
          "The Jennie Project",
          "The Poof Point",
          "Halloweentown II: Kalabar's Revenge",
          "Double Teamed",
          "Cadet Kelly",
          "Tru Confessions",
          "Get a Clue",
          "Gotta Kick It Up!",
          "The Even Stevens Movie",
          "Eddie's Million Dollar Cook-Off",
          "The Cheetah Girls",
          "Full-Court Miracle",
          "Pixel Perfect",
          "Going to the Mat",
          "Zenon: Z3",
          "Tiger Cruise",
          "Halloweentown High",
          "Now You See It...",
          "Kim Possible Movie: So the Drama",
          "The Proud Family Movie",
          "High School Musical"
        ],
        [
          "PIxar",          "FALSE",          "All things Pixar",          "Boo",          "Sulley",          "Mike Wazowski",          "Randy Boggs",          "Roz",          "Monsters Inc.",          "Toy Story",          "Buzz Lightyear",          "Woody",          "Lots-o'-Huggin Bear",          "Slinky Dog",          "Rex",          "Mr. Potato Head",          "Jessie",          "Hamm",          "Mrs. Potato Head",          "Mr. Pricklepants",          "Sparks",          "Sid",          "Green Army Men",          "Andy",          "Buttercup",          "Trixie",          "Stretch",          "Bookworm",          "Big Baby",          "Chunk",          "Dolly",          "Twitch",          "Little Bo Peep",          "Forky",          "Duke Caboom",          "Up",          "Russell",          "Carl Fredricksen",          "Dug",          "The Incredibles",          "Dash",          "Frozone",          "Coco",          "Ernesto de la Cruz",          "Lightning McQueen",          "Doc Hudson",          "Cars 3",          "Finding Dory",          "Hank",          "Dory",          "Nemo",          "Marlin",          "Bailey",          "Destiny",          "Gerald",          "Fluke & Rudder",          "Great Barrier Reef",          "Monsters University",          "Don Carlton",          "Terri & Terry Perry",          "Mrs. Squibbles",          "Archie the Scare Pig",          "Brave",          "Merida",          "Queen Elinor",          "Angus",          "Toy Story 3",          "Wall-e",          "Eve",          "M-O",          "Captain",          "Axiom",          "Ratatouille",          "Remy",          "Auguste Gusteau",          "Linguini",          "Colette",          "Anton Ego",          "A Bug's Life",          "Flik",          "Princess Atta",          "Heimlich",          "Hopper",          "Molt",          "Mater",          "Sally",          "Sarge",          "Ramone",          "Flo",          "Gill",          "Nigel",          "\"Mine, Mine, Mine\"",          "Toy Story 2",          "Toy Story 4",          "Inside Out",          "The Good Dinosaur",          "Arlo"        ],
        [
          "Disneyland Paris",
          "FALSE",
          "The magic you can experience at Disneyland Paris",
          "Mickey’s PhilharMagic",
          "it's a small world'",
          "Adventure Isle",
          "Alice's Curious Labyrinth",
          "Big Thunder Mountain",
          "Blanche-Neige et les Sept Nains",
          "Buzz Lightyear Laser Blast",
          "Casey Jr. – le Petit Train du Cirque",
          "Crush's Coaster",
          "Discovery Arcade",
          "Disney Studio 1",
          "Dumbo the Flying Elephant",
          "Frontierland Playground",
          "Horse-Drawn Streetcars",
          "La Cabane des Robinson",
          "La Galerie de la Belle au Bois Dormant",
          "La Tanière du Dragon",
          "Le Carrousel de Lancelot",
          "Le Passage Enchanté d'Aladdin",
          "Le Pays des Contes de Fées",
          "Les Tapis Volants - Flying Carpets Over Agrabah®",
          "Les Voyages de Pinocchio",
          "Liberty Arcade",
          "Mad Hatter's Tea Cups",
          "Main Street Vehicles",
          "Meet Mickey Mouse",
          "Orbitron®",
          "Peter Pan's Flight",
          "Phantom Manor",
          "Pirate Galleon",
          "Pirates of the Caribbean",
          "Pirates' Beach",
          "Princess Pavilion",
          "RC Racer",
          "Ratatouille: The Adventure",
          "Rustler Roundup Shootin' Gallery",
          "Sleeping Beauty Castle",
          "Slinky® Dog Zigzag Spin",
          "Star Tours: The Adventures Continue*",
          "Star Wars Hyperspace Mountain",
          "Studio Tram Tour®: Behind the Magic",
          "The Twilight Zone Tower of Terror – A new Dimension of Chills",
          "Thunder Mesa Riverboat Landing",
          "Toy Soldiers Parachute Drop",
          "Welcome to Starport: A Star Wars Encounter",
          "Cowboy Cookout Barbecue",
          "Disneyland Park",
          "Walt Disney Studios Park",
          "Main Street U.S.A.",
          "Frontierland",
          "Adventureland",
          "Fantasyland",
          "Discoveryland",
          "Front Lot",
          "Production Courtyard",
          "Toon Studio",
          "Backlot",
          "Toad Hall Restaurant",
          "Bistrot Chez Rémy",
          "Colonel Hathi’s Pizza Outpost",
          "Silver Spur Steakhouse",
          "Restaurant Hakuna Matata",
          "Buffalo Bill's Wild West Show",
          "Planet Hollywood",
          "Inventions",
          "Casey's Corner",
          "Annette's Diner",
          "Café Mickey",
          "Captain Jack's - Restaurant des Pirates",
          "Disneyland Hotel",
          "Disney's Hotel New York",
          "Disney's Newport Bay CLub",
          "Disney's Sequoia Lodge",
          "Disney's Hotel Chyenne",
          "Disney's Hotel Santa Fe",
          "Mickey Mouse",
          "Minnie Mouse",
          "Donald Duck",
          "Goofy",
          "Pluto",
          "Chip 'n' Dale",
          "Captain Hook",
          "Winnie the Pooh",
          "Eeyore",
          "Tigger",
          "Buzz Lightyear",
          "Woody",
          "Jessie",
          "Gepetto",
          "Jafar",
          "Mary Poppins",
          "Pinocchio",
          "Spiderman",
          "Baymax",
          "Peter Pan",
          "Aladdin",
          "Jasmine",
          "Elsa",
          "Anna",
          "Chewbacca",
          "Ariel",
          "Snow White",
          "Cinderella",
          "Belle",
          "Daisy Duck",
          "Alice",
          "Disney Illuminations",
          "Mickey's PhilharMagic",
          "Lilo",
          "Stitch",
          "Mickey et le Magicien"
        ]
      ]
    }
  ]
}
